using HRWatch.Domain.Common;

namespace HRWatch.Domain.Entities;

/// <summary>
/// One row in the weekly report — represents a single employee's summary for the week.
/// Generated by ComplianceEvaluator domain service.
/// </summary>
public class WeeklyReportEntry : AuditableEntity
{
    public Guid WeeklyReportId { get; private set; }
    public WeeklyReport? WeeklyReport { get; private set; }

    public Guid EmployeeId { get; private set; }
    public Employee? Employee { get; private set; }

    public string EmployeeFullName  { get; private set; } = string.Empty;
    public string EmployeeDepartment { get; private set; } = string.Empty;

    public int DaysPresent    { get; private set; }
    public int DaysAbsent     { get; private set; }
    public int DaysLate       { get; private set; }
    public int DaysOnLeave    { get; private set; }
    public int ViolationCount { get; private set; }

    /// Total hours worked during the week
    public decimal TotalWorkHours { get; private set; }

    /// Compliance score for this employee this week (0-100)
    public decimal ComplianceScore { get; private set; }

    public string? Summary { get; private set; }

    // ── Factory ──────────────────────────────────────────────────────────────

    public static WeeklyReportEntry Create(
        Guid weeklyReportId,
        Guid employeeId,
        string employeeFullName,
        string employeeDepartment,
        int daysPresent,
        int daysAbsent,
        int daysLate,
        int daysOnLeave,
        decimal totalWorkHours,
        int violationCount,
        decimal complianceScore) => new()
    {
        WeeklyReportId      = weeklyReportId,
        EmployeeId          = employeeId,
        EmployeeFullName    = employeeFullName,
        EmployeeDepartment  = employeeDepartment,
        DaysPresent         = daysPresent,
        DaysAbsent          = daysAbsent,
        DaysLate            = daysLate,
        DaysOnLeave         = daysOnLeave,
        TotalWorkHours      = totalWorkHours,
        ViolationCount      = violationCount,
        ComplianceScore     = complianceScore,
        CreatedAt           = DateTime.UtcNow,
        CreatedBy           = "system"
    };

    private WeeklyReportEntry() { }
}
